flowchart TD
    classDef removed fill:#666,color:#fff;
    
A[/9\] --- B    
A --- C

B[\5/] --- D
B --- E
C[\9/] --- F
C --- G

D[/7\] --- H
D --- I
E[/5\] --- J
E --- K
F[/9\] --- L
F --- M
G[/12\] --- N
G --- O
G --- P

H[\7/] --- a(8)
H --- b(7)
I[\2/] --- c(9)
I --- d(2)
I --- e(11)
J[\5/] --- f(5)
K[\3/] --- g(10)
K --- h(3)
L[\4/] --- i(12)
L --- k(4)
L --- l(6)
M[\9/] --- m(9)
N[\6/] --- n(6)
O[\12/] --- o(14)
O --- p(12)
P[\2/] --- q(20)
P --- r(2)
P --- s(10)