flowchart TD
    classDef removed fill:#666,color:#fff;
    
A[/A\] --- B    
A --- C

B[\B/] --- D
B --- E
C[\C/] --- F
C --- G

D[/D\] --- H
D --- I
E[/E\] --- J
E --- K
F[/F\] --- L
F --- M
G[/G\] --- N
G --- O
G --- P

H[\H/] --- a(8)
H --- b(7)
I[\I/] --- c(9)
I --- d(2)
I --- e(11)
J[\J/] --- f(5)
K[\K/] --- g(10)
K --- h(3)
L[\L/] --- i(12)
L --- k(4)
L --- l(6)
M[\M/] --- m(9)
N[\N/] --- n(6)
O[\O/] --- o(14)
O --- p(12)
P[\P/] --- q(20)
P --- r(2)
P --- s(10)