flowchart TD
    classDef removed fill:#666,color:#fff;
    
    a(a:14) --> b(b:16)
    a(a:14) --> c(c:14)

    c(c:14) --> e(e:17)
    c(c:14) --> d(d:16)

    d(d:16) --> e1(e:16)

    e1(e:16) --> b1(b:36)
    e1(e:16) --> z(z:17)