flowchart LR
    classDef removed fill:#666,color:#fff;
    
    a1a2a3 --> b1a2a3
    a1a2a3 --> c1a2a3
    a1a2a3 --> d1a2a3
    a1a2a3 --> b2a2a3
    a1a2a3 --> c3a2a3
    a1a2a3 --> d4a2a3

    a1a2a3 --> a1b2a3
    a1a2a3 --> a1c2a3
    a1a2a3 --> a1d2a3
    a1a2a3 --> a1b1a3
    a1a2a3 --> a1b3a3
    a1a2a3 --> a1c4a3

    a1a2a3 --> a1a2b3
    a1a2a3 --> a1a2c3
    a1a2a3 --> a1a2d3
    a1a2a3 --> a1a2b4
    a1a2a3 --> a1a2b2
    a1a2a3 --> a1a2c1

    b1a2a3 --> c1a2a3
    b1a2a3 --> d1a2a3
    b1a2a3 --> c2a2a3
    b1a2a3 --> d3a2a3
    b1a2a3 --> b2a2a3
    b1a2a3 --> b3a2a3
    b1a2a3 --> b4a2a3